services:
  - type: web
    name: screenflow-api
    runtime: node
    buildCommand: npm install
    startCommand: npm start --workspace=backend
    envVars:
      - key: JWT_SECRET_KEY
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: "https://screenflow-dashboard.onrender.com,http://localhost:5173"
      - key: HEARTBEAT_TIMEOUT_SECONDS
        value: "90"
      - key: RENDER
        value: "true"
      - key: API_BASE_URL
        value: "https://screen-api-6sac.onrender.com"

  - type: web
    name: screenflow-dashboard
    runtime: static
    buildCommand: npm install && npm run build --workspace=frontend
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

